/**
 * Root Layout - Bố cục chính của toàn bộ ứng dụng
 * 
 * Tác dụng:
 * - Khai báo HTML, head, body (thẻ gốc)
 * - Tải font chữ và CSS toàn cục
 * - Bọc toàn bộ ứng dụng bên trong Providers (để React Query hoạt động)
 */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";  // Tải CSS toàn cục (áp dụng cho tất cả trang)
import Providers from './providers';

// Tải font chữ từ Google Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",  // Lưu dưới dạng CSS variable
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata được hiển thị trên trình duyệt (title, description, etc.)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col text-[50px]">
        {/* 2. Bọc toàn bộ nội dung của ứng dụng (children) bên trong Providers */}
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
